# Use official Node.js image as base
FROM 058264490987.dkr.ecr.ap-south-1.amazonaws.com/dockerimages:frontend-base

# Set working directory
WORKDIR /usr/src/app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install express body-parser

# Copy all source code
COPY . .

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["npm", "start"]