version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      # - echo $AWS_DEFAULT_REGION
      - aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 058264490987.dkr.ecr.ap-south-1.amazonaws.com/dockerimages
      - REPO_FRONTEND=058264490987.dkr.ecr.ap-south-1.amazonaws.com/nodejs/frontend     
      - REPO_BACKEND=058264490987.dkr.ecr.ap-south-1.amazonaws.com/nodejs/backend
  build:
    commands:
      # Frontend
      - echo testing frontend application using rspec
      - path=`pwd`
      - cd $path/frontend
      - docker build -t $REPO_FRONTEND:frontend .
      - docker tag $RREPO_FRONTEND:latest $REPO_FRONTEND:${CODEBUILD_BUILD_NUMBER}
      - docker push $REPO_FRONTEND:${CODEBUILD_BUILD_NUMBER}

      - cd $path/backend
      - echo building backend - tagging and pushing docker image.
      - docker build -t $REPO_BACKEND:backend .
      - docker tag $REPO_BACKEND:latest $REPO_BACKEND:${CODEBUILD_BUILD_NUMBER}
      - docker push $RREPO_BACKEND:${CODEBUILD_BUILD_NUMBER}
      # - docker tag $REPOSITORY_NAME:frontend $REPOSITORY_URI:frontend-${CODEBUILD_BUILD_NUMBER}
      # - docker push $REPOSITORY_URI:frontend-${CODEBUILD_BUILD_NUMBER}

#       # Backend
#       - echo building frontend - tagging and pushing docker image.
#       - docker build -t $REPOSITORY_NAME:app -f /Users/vedika/Documents/Home-lab/project/frontend/dockerfile .
#       - docker tag $REPOSITORY_NAME:app $REPOSITORY_URI:app-${CODEBUILD_BUILD_NUMBER}
#       - docker push $REPOSITORY_URI:app-${CODEBUILD_BUILD_NUMBER}
  
# artifacts:
#   files: imagedefinitions.json