version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - backend
  backend:
    build: ./backend
    ports:
      - "3001:3001"
    links:
      - database
  database:
    image: mongo
    ports:
      - "27017:27017"